CREATE EXTENSION IF NOT EXISTS CITEXT;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id        SERIAL PRIMARY KEY NOT NULL,
  email     CITEXT UNIQUE NOT NULL,
  phone     CITEXT UNIQUE NOT NULL,
  password  CITEXT NOT NULL
);
